server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html/farmazed-web;
    index index.html;

    location = /qr {
        return 302 https://farmazed-tracker-267037695065.us-central1.run.app/qr;
    }

    location /portal/ {
        root /usr/share/nginx/html/farmazed-web;
        try_files $uri $uri/ /login.html;
    }

    location /admin/ {
        root /usr/share/nginx/html/farmazed-web;
        try_files $uri $uri/ /admin/casos.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
