/**
 * seed_pricing_24sep.js — TAREA 23 (PM_COMMENTS §H.8, parte Precios).
 *
 * Tarifario NUEVO del 24-sep (xlsx "Actualización de nuestros precios para la
 * plataforma - copia.xlsx", _Zelky-Drive-2026-09-25/F04-...), más reciente que
 * el canónico del 12-sep que ya vive en seed_pricing.js. Por instrucción
 * explícita del PM: se carga SOLO EN EL EMULADOR, como categorías NUEVAS (ids
 * distintos, sufijo _24sep) — seed_pricing.js (el que corre en producción) NO
 * se toca. Ver organizacion/10_DIFF_PRECIOS_24SEP.md para la comparación
 * completa categoría por categoría.
 *
 * ⚠️  SOLO EMULADOR. Se niega a correr sin FIRESTORE_EMULATOR_HOST — en
 * producción, ningún precio cambia sin que Rick lo apruebe (es dinero).
 *
 * Uso:
 *   FIRESTORE_EMULATOR_HOST=localhost:8090 FIREBASE_PROJECT_ID=demo-farmazed \
 *   node scripts/seed_pricing_24sep.js
 */

if (!process.env.FIRESTORE_EMULATOR_HOST) {
  console.error('❌ seed_pricing_24sep.js SOLO corre contra el emulador — no toca producción.');
  process.exit(1);
}

const admin = require('firebase-admin');
if (!admin.apps.length) {
  admin.initializeApp({ projectId: process.env.FIREBASE_PROJECT_ID || 'demo-farmazed' });
}
const db = admin.firestore();

const COMPONENT_KEYS = [
  'honorarios_farmazed', 'honorarios_abogado', 'gastos_adicionales',
  'refrendo_cnf', 'tasa_dnfd_servicio', 'tasa_dnfd_tramite', 'iea', 'tasa_mef',
];

// Fila con #REF! en el xlsx original (Renovación por trámite abreviado, fila 42):
// el IEA/Total de tasas/Total general vienen ROTOS en la fuente — se cargan como
// `null`, NUNCA se inventa un número para tapar el hueco (mismo criterio que
// formularios 'por_confirmar', TAREA 17).
const PRICING_DATA_24SEP = [
  {
    id: 'med_abreviado_sintesis_24sep',
    name: 'Síntesis química Procedimiento abreviado',
    grupo: 'Registros Nuevos (Abreviado) — 24-sep',
    components: {
      honorarios_farmazed: 1200,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 750,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_abreviado_biologicos_24sep',
    name: 'Biológicos Biotecnológicos   , Procedimiento Abreviado',
    grupo: 'Registros Nuevos (Abreviado) — 24-sep',
    components: {
      honorarios_farmazed: 1200,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 750,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_abreviado_prioridad_innovadores_24sep',
    name: 'Prioridad para el trámite de solicitud de registros sanitarios de medicamentos innovadores inicial, renovación y modificación',
    grupo: 'Registros Nuevos (Abreviado) — 24-sep',
    components: {
      honorarios_farmazed: 1000,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 750,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_abreviado_suplementos_24sep',
    name: 'Suplementos Vitamínicos, Alimenticios y dietéticos    Procedimiento Abreviado',
    grupo: 'Registros Nuevos (Abreviado) — 24-sep',
    components: {
      honorarios_farmazed: 1200,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 750,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_abreviado_homeopaticos_24sep',
    name: 'Productos Homeopáticos    Procedimiento Abreviado',
    grupo: 'Registros Nuevos (Abreviado) — 24-sep',
    components: {
      honorarios_farmazed: 1200,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 750,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_abreviado_radiofarmacos_24sep',
    name: 'Radiofármacos   Procedimiento Abreviado',
    grupo: 'Registros Nuevos (Abreviado) — 24-sep',
    components: {
      honorarios_farmazed: 1200,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 750,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_abreviado_huerfanos_24sep',
    name: 'Huérfanos    Procedimiento Abreviado',
    grupo: 'Registros Nuevos (Abreviado) — 24-sep',
    components: {
      honorarios_farmazed: 1200,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 50,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_mutuo_acuerdo_24sep',
    name: 'Mutuo Acuerdo',
    grupo: 'Registros Nuevos (Abreviado) — 24-sep',
    components: {
      honorarios_farmazed: 1000,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 500,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_abreviado_wla_who_24sep',
    name: 'Abreviado WLA WHO',
    grupo: 'Registros Nuevos (Abreviado) — 24-sep',
    components: {
      honorarios_farmazed: 1200,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 750,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_regular_general_24sep',
    name: 'Procedimiento Regular',
    grupo: 'Registros Nuevos (Regular) y otros — 24-sep',
    components: {
      honorarios_farmazed: 1000,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 500,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_regular_sintesis_24sep',
    name: 'Síntesis química Procedimiento Regular',
    grupo: 'Registros Nuevos (Regular) y otros — 24-sep',
    components: {
      honorarios_farmazed: 1000,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 500,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_regular_naturales_24sep',
    name: 'Productos Naturales Registro Regular',
    grupo: 'Registros Nuevos (Regular) y otros — 24-sep',
    components: {
      honorarios_farmazed: 800,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 500,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_regular_gases_24sep',
    name: 'Gases  Medicinales  Registro Regular',
    grupo: 'Registros Nuevos (Regular) y otros — 24-sep',
    components: {
      honorarios_farmazed: 800,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 500,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_regular_contraste_24sep',
    name: 'Medicamentos de Contraste  Registro Regular',
    grupo: 'Registros Nuevos (Regular) y otros — 24-sep',
    components: {
      honorarios_farmazed: 800,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 500,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'cosmeticos_10_variedades_24sep',
    name: 'Expedición de registro sanitario para cosméticos por cada 10 variedades adicionales',
    grupo: 'Registros Nuevos (Regular) y otros — 24-sep',
    components: {
      honorarios_farmazed: 800,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 500,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'med_regular_huerfano_24sep',
    name: 'Huérfano',
    grupo: 'Registros Nuevos (Regular) y otros — 24-sep',
    components: {
      honorarios_farmazed: 400,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 50,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'intercambiabilidad_24sep',
    name: 'Intercambiabilidad',
    grupo: 'Registros Nuevos (Regular) y otros — 24-sep',
    components: {
      honorarios_farmazed: 800,
      honorarios_abogado: 250,
      gastos_adicionales: 605,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 250,
      tasa_dnfd_tramite: 400,
      iea: 1500,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'renovacion_sintesis_quimica_24sep',
    name: 'Renovación de registro sanitario para productos farmacéuticos de síntesis química',
    grupo: 'Renovaciones — 24-sep',
    components: {
      honorarios_farmazed: 1000,
      honorarios_abogado: 250,
      gastos_adicionales: 650,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 500,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'renovacion_innovadores_biologicos_24sep',
    name: 'Renovación de registro sanitario para productos farmacéuticos innovadores, biológicos, biotecnológicos y biosimilares',
    grupo: 'Renovaciones — 24-sep',
    components: {
      honorarios_farmazed: 1000,
      honorarios_abogado: 250,
      gastos_adicionales: 650,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 750,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'renovacion_abreviado_24sep',
    name: 'Renovación de registro sanitario por trámite abreviado',
    grupo: 'Renovaciones — 24-sep',
    components: {
      honorarios_farmazed: 1200,
      honorarios_abogado: 250,
      gastos_adicionales: 650,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 750,
      iea: null /* #REF! en el xlsx original */,
      tasa_mef: 25,
    },
    notes: 'Fila con #REF! en el xlsx 24-sep (fórmula rota en la fuente) — IEA/Total de tasas/Total general sin dato, no inventado.',
  },
  {
    id: 'renovacion_cosmeticos_24sep',
    name: 'Renovación de registro sanitario para cosméticos y similares, y productos sanitarios de higiene personal',
    grupo: 'Renovaciones — 24-sep',
    components: {
      honorarios_farmazed: 1000,
      honorarios_abogado: 250,
      gastos_adicionales: 650,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 500,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'renovacion_otros_plaguicidas_24sep',
    name: 'Renovación de registro sanitario de otros productos para la salud humana y de Registro Sanitario de plaguicidas de uso doméstico y de salud pública para uso profesional',
    grupo: 'Renovaciones — 24-sep',
    components: {
      honorarios_farmazed: 800,
      honorarios_abogado: 250,
      gastos_adicionales: 650,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 500,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'renovacion_intercambiabilidad_24sep',
    name: 'Renovación de la intercambiabilidad bajo la condición de medicamento de Referencia o Intercambiable',
    grupo: 'Renovaciones — 24-sep',
    components: {
      honorarios_farmazed: 800,
      honorarios_abogado: 250,
      gastos_adicionales: 650,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 250,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'renovacion_reconocimiento_mutuo_24sep',
    name: 'Renovación de registro sanitario por reconocimiento mutuo',
    grupo: 'Renovaciones — 24-sep',
    components: {
      honorarios_farmazed: 850,
      honorarios_abogado: 250,
      gastos_adicionales: 650,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 500,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'renovacion_fuentes_alternas_24sep',
    name: 'Renovación de registro sanitario para medicamentos de fuentes alternas de fabricación',
    grupo: 'Renovaciones — 24-sep',
    components: {
      honorarios_farmazed: 1000,
      honorarios_abogado: 250,
      gastos_adicionales: 650,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 500,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_ampliacion_de_presentacion_24sep',
    name: 'Ampliación de presentación',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_o_modificacion_en_el_nombre_comer_24sep',
    name: 'Cambio o modificación en el nombre comercial',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_de_razon_social_del_fabricante_em_24sep',
    name: 'Cambio de razón social del fabricante, empacador o titular en el certificado de registro',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_en_la_monografia_inserto_adicion_24sep',
    name: 'Cambio en la monografía, inserto, adición de inserto',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_en_el_periodo_de_vida_util_24sep',
    name: 'Cambio en el periodo de vida útil',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_en_las_condiciones_de_almacenamie_24sep',
    name: 'Cambio en las condiciones de almacenamiento',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_de_empacador_primario_24sep',
    name: 'Cambio de empacador primario',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_de_empacador_secundario_24sep',
    name: 'Cambio de empacador secundario',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_o_adicion_en_el_tipo_de_material_24sep',
    name: 'Cambio o adición en el tipo de material del empaque primario o del sistema envase cierre',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_adicion_de_un_nuevo_empaque_primario_24sep',
    name: 'Adición de un nuevo empaque primario',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_de_titular_24sep',
    name: 'Cambio de Titular',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_de_origen_o_en_caso_de_fabricacio_24sep',
    name: 'Cambio de origen o en caso de fabricación por terceros: a. Cambio de Fabricante. b. Cambio de fabricante y de país de origen',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_de_modalidad_de_venta_24sep',
    name: 'Cambio de modalidad de venta',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_de_excipientes_24sep',
    name: 'Cambio de excipientes',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_de_informacion_o_diseno_en_el_eti_24sep',
    name: 'Cambio de información o diseño en el etiquetado primario y secundario',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_en_el_sitio_de_fabricacion_dentro_24sep',
    name: 'Cambio en el sitio de fabricación dentro de un mismo país',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_en_el_representante_legal_o_del_p_24sep',
    name: 'Cambio en el representante legal o del profesional responsable',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_o_actualizacion_en_las_especifica_24sep',
    name: 'Cambio o actualización en las especificaciones del producto terminado',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_o_actualizacion_en_la_metodologia_24sep',
    name: 'Cambio o actualización en la metodología analítica',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_o_ampliacion_de_indicaciones_tera_24sep',
    name: 'Cambio o ampliación de indicaciones terapéuticas',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_autorizacion_de_comercializacion_conjunt_24sep',
    name: 'Autorización de comercialización conjunta (Co-Empaques)',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_modificacion_de_las_vias_de_administraci_24sep',
    name: 'Modificación de las vías de administración',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_del_fabricante_del_diluyente_24sep',
    name: 'Cambio del Fabricante del diluyente',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_modificacion_de_la_denominacion_del_prin_24sep',
    name: 'Modificación de la denominación del principio activo',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_del_representante_legal_que_resid_24sep',
    name: 'Cambio del Representante Legal que reside en el país autorizado por el titular',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 25,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_cambio_del_profesional_responsable_autor_24sep',
    name: 'Cambio del Profesional responsable autorizado por el titular',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 25,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_otros_cambios_en_la_informacion_aportada_24sep',
    name: 'Otros cambios en la información aportada en la obtención del Registro Sanitario',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 200,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
  {
    id: 'mod_modificaciones_para_medicamentos_huerfan_24sep',
    name: 'Modificaciones para Medicamentos Huérfanos',
    grupo: 'Modificaciones — 24-sep',
    components: {
      honorarios_farmazed: 50,
      honorarios_abogado: 250,
      gastos_adicionales: 250,
      refrendo_cnf: 50,
      tasa_dnfd_servicio: 50,
      tasa_dnfd_tramite: 200,
      iea: 0,
      tasa_mef: 25,
    },
    notes: '',
  },
];

async function seed() {
  const batch = db.batch();
  const now = new Date().toISOString();
  let total = 0;
  for (const item of PRICING_DATA_24SEP) {
    const total_ = COMPONENT_KEYS.reduce((s, k) => s + (item.components[k] === null ? 0 : Number(item.components[k]) || 0), 0);
    const totalCuadra = !COMPONENT_KEYS.some(k => item.components[k] === null);
    const doc = { ...item, total: totalCuadra ? total_ : null, updatedAt: now, updatedBy: 'seed_24sep' };
    const ref = db.collection('pricing').doc(item.id);
    batch.set(ref, doc);
    total += 1;
  }
  await batch.commit();
  console.log(`✅ Seeded ${total} categorías del tarifario 24-sep (ids con sufijo _24sep, no pisan las de seed_pricing.js).`);
}

seed().then(() => process.exit(0)).catch(err => {
  console.error('❌ Seed 24-sep error:', err);
  process.exit(1);
});
